<My_Relative_Layout>:
    canvas:
        Color:
            rgba:0,0,0,1
        Line:
            rectangle:0,0,self.size[0],self.size[1]
<My_Button_Layout>:
<My_Label_Layout>:
    font_size:'30sp'
    color:0,0,0,1
    # canvas:
    #     Color:
    #         rgba:0,0,0,1
    #     Line:
    #         rectangle:self.pos[0],self.pos[1],self.size[0],self.size[1]
<My_Text_Input>:
    